name: Smart Clinic CI

on:
  push:
    branches:
      - main
      - develop
      - feature/*
  pull_request:
    branches:
      - main
      - develop

jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restore dependencies
        working-directory: SmartClinicManagementSystem
        run: dotnet restore SmartClinicManagementSystem.slnx

      - name: Build solution
        working-directory: SmartClinicManagementSystem
        run: dotnet build SmartClinicManagementSystem.slnx --configuration Release --no-restore

      - name: Run automated tests
        working-directory: SmartClinicManagementSystem
        run: dotnet test SmartClinicManagementSystem.slnx --configuration Release --no-build --verbosity normal